  $ $JBUILDER build -j0 --root . @install
      ocamldep a/ppx/a.depends.ocamldep-output
        ocamlc a/ppx/a.{cmi,cmo,cmt}
      ocamlopt a/ppx/a.{cmx,o}
      ocamlopt a/ppx/a.{a,cmxa}
        ocamlc a/ppx/a.cma
      ocamlopt a/ppx/a.cmxs
      ocamldep a/kernel/a_kernel.depends.ocamldep-output
        ocamlc a/kernel/a_kernel.{cmi,cmo,cmt}
      ocamlopt a/kernel/a_kernel.{cmx,o}
      ocamlopt a/kernel/a_kernel.{a,cmxa}
        ocamlc a/kernel/a_kernel.cma
      ocamlopt a/kernel/a_kernel.cmxs
      ocamlopt .ppx/a.kernel/ppx.exe
      ocamlopt .ppx/a/ppx.exe
           ppx b/b.pp.ml
      ocamldep b/b.depends.ocamldep-output
        ocamlc b/b.{cmi,cmo,cmt}
      ocamlopt b/b.{cmx,o}
      ocamlopt b/b.{a,cmxa}
        ocamlc b/b.cma
      ocamlopt b/b.cmxs
